#! /usr/bin/env python3

from plenum.common.test_network_setup import TestNetworkSetup

from sovrin.common.config_util import getConfig
from sovrin.common.txn import getTxnOrderedFields

config = getConfig()
keepDir = config.baseDir
portsStart = 9700


if __name__ == "__main__":
    TestNetworkSetup.bootstrapTestNodes(portsStart, keepDir,
                                        config.poolTransactionsFile,
                                        config.domainTransactionsFile,
                                        getTxnOrderedFields())
