#!/usr/bin/env bash
set -e

GACTION=$1

dirs=( "sovrin-priv" "plenum-priv" "anoncreds-priv" "ledger-priv" )

# quiet pushd
pushd() {
  command pushd "$@" > /dev/null
}

# quiet popd
popd() {
  command popd "$@" > /dev/null
}

for dir in "${dirs[@]}"
do
  pushd ../$dir
  echo '----------' 'RUNNING' $1 'ON' $(pwd) '----------'
  git $GACTION
  popd
done
