#!/usr/bin/env bash

echo -e "\nWhich repos:"
echo -e "  0. All following repos"
echo -e "  1. Sovrin"
echo -e "  2. Plenum"
echo -e "  3. Ledger"
echo -e "  4. Anoncreds"
read -ep $'Enter your choice (For example: 0 OR 1,2,3 etc): ' repos
if [ "$repos" == "0" ]; then
    repos="1,2,3,4"
fi;

echo -e "\nUpload to:"
echo -e "  0. Both (pypi and pypitest)"
echo -e "  1. Only pypi"
echo -e "  2. Only pypitest"
read -ep $'Enter your choice: ' -i '0' dest

read -ep $'\nDo you want to use setup.py file (Y/n): ' -i 'n' usesetupfile

echo -e "\nVerify:"
echo -e "  Selected repos: $repos"
echo -e "  Use setup.py file: $usesetupfile"
echo -e "  Upload to choice: $dest"

read -ep $'\nContinue (Y/n)? ' -i 'Y' cont

if [ $cont != "Y" ];then
    exit
fi;


curDir=`pwd`
scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo -e "Current script directory: $scriptDir"
cd $scriptDir
cd ../..
allRepoParentDir=`pwd`

suffix="-priv"
if [ "$usesetupfile" == "Y" ]; then
    suffix = "-pub"
fi;

export IFS=","
for repo in $repos
do
    cd $allRepoParentDir

    repoName=""
    if [ $repo -eq "1" ]; then
        repoName="sovrin$suffix"
    elif [ $repo -eq "2" ]; then
        repoName="plenum$suffix"
    elif [ $repo -eq 3 ]; then
        repoName="ledger$suffix"
    elif [ $repo -eq 4 ]; then
        repoName="anoncreds$suffix"
    else
        echo -e "Not supported this repo $repo"
        exit
    fi
    cd $repoName
    cdir=`pwd`
    echo -e "\n\nabout to start uploading $repoName... [cur dir: $cdir]"

    if [ "$usesetupfile" != "Y" ]; then
        echo -e "Temporary changes to use setup-dev.py file"
        mv setup.py setup-st.py
        mv setup-dev.py setup.py
    fi;

    if [[ "$dest" == "0" || "$dest" == "2" ]]; then
        echo -e "About to upload to pypitest..."
        python setup.py register -r pypitest
        python setup.py sdist upload -r pypitest
    fi;

    if [[ "$dest" == "0" || "$dest" == "1" ]]; then
        echo -e "About to upload to pypi..."
        python setup.py register -r pypi
        python setup.py sdist upload -r pypi
    fi;

    if [ "$usesetupfile" != "Y" ]; then
        echo -e "Reverting back temporary changes to use setup-dev.py file"
        mv setup.py setup-dev.py
        mv setup-st.py setup.py
    fi;

    echo -e "finished uploading $repoName to pypi\n"
done

cd $curDir