#! /usr/bin/env python3

import os
import sys

from plenum.common.types import HA

from plenum.common.looper import Looper
from plenum.common.raet import initRemoteKeep
from ioflo.aid.consoling import Console
from plenum.common.util import setupLogging, TRACE_LOG_LEVEL, getRAETLogLevelFromConfig
from sovrin.common.util import getConfig
from sovrin.server.node import Node

config = getConfig()
keepDir = os.path.expanduser(config.baseDir)

if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Provide name and 2 port numbers for running the node "
              "and client stacks")
        exit()
    else:

        RAETVerbosity = getRAETLogLevelFromConfig("RAETLogLevel",
                                                  Console.Wordage.mute)

        selfName = sys.argv[1]
        ha = HA("0.0.0.0", int(sys.argv[2]))
        cliha = HA("0.0.0.0", int(sys.argv[3]))

        logFileName = os.path.join(config.baseDir, selfName + ".log")
        print("You can find logs in {}".format(logFileName))
        setupLogging(TRACE_LOG_LEVEL,
                     RAETVerbosity,
                     filename=logFileName)

        with Looper(debug=True) as looper:
            node = Node(selfName, nodeRegistry=None, basedirpath=keepDir, ha=ha,
                        cliha=cliha)
            looper.add(node)
            looper.run()
